apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-pedidos
  namespace: gestion-pedidos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-pedidos
  template:
    metadata:
      labels:
        app: backend-pedidos
    spec:
      containers:
      - name: backend
        image: joacosua/gestion-pedidos-backend:latest
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-pedidos-service
  namespace: gestion-pedidos
spec:
  selector:
    app: backend-pedidos
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP 